worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/openresty.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    lua_package_path "/etc/nginx/lua/?.lua;;";

    log_format json_log escape=json
        '{'
            '"time":"$time_iso8601",'
            '"method":"$request_method",'
            '"path":"$request_uri",'
            '"status":$status,'
            '"duration_ms":$request_time,'
            '"bytes_sent":$body_bytes_sent,'
            '"client_ip":"$remote_addr",'
            '"upstream":"$upstream_addr",'
            '"user_agent":"$http_user_agent"'
        '}';

    access_log /var/log/nginx/access.log json_log;

    sendfile           on;
    keepalive_timeout  65;
    gzip               on;

    limit_req_zone $binary_remote_addr zone=api_ratelimit:10m rate=20r/s;
    limit_req_zone $binary_remote_addr zone=auth_ratelimit:10m rate=5r/s;

    include /etc/nginx/conf.d/*.conf;
}
