upstream spring_backend {
    server spring-boot-1:8080;
    server spring-boot-2:8080;
    keepalive 32;
}

upstream nextjs_frontend {
    server nextjs:3000;
    keepalive 16;
}

upstream keycloak {
    server keycloak:8080;
    keepalive 16;
}
